modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="werewolf"
version="1.0.0"
displayName="Werewolf"
authors="Rithys, Runa, R9r4y"
description='''${mod_description}'''

[[dependencies.werewolf]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.werewolf]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
